"""Initial migration

Revision ID: 867bdc60b03d
Revises: 18fcf9f47d1a
Create Date: 2023-06-14 14:34:58.312415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867bdc60b03d'
down_revision = '18fcf9f47d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
